// Generated by CoffeeScript 1.6.2
$(function() {
  var console, controller;

  console = $(".console");
  return controller = console.console({
    promptLabel: "scheme>",
    commandHandle: function(line) {
      if (line) {
        return [
          {
            msg: "you typed " + line,
            className: "jquery-console-message-value"
          }
        ];
      } else {
        return [
          {
            className: "jquery-console-message-value"
          }
        ];
      }
    },
    keywords: ["define", "let", "cond"],
    cols: 40,
    completeHandle: function(prefix) {
      var keyword, keywords, ret, _i, _len;

      keywords = this.keywords;
      ret = [];
      for (_i = 0, _len = keywords.length; _i < _len; _i++) {
        keyword = keywords[_i];
        if (keyword.lastIndexOf(prefix, 0) === 0) {
          ret.push(keyword.substring(prefix.length));
        }
      }
      return ret;
    }
  });
});
